name: Publish to official repository

inputs:
  privkey:
    description: Base64 encoded private key
    required: true
  filepath:
    description: The full path of the file to upload
    required: true

runs:
  using: composite  

  steps:    
    - name: Install missing packages
      shell: sh
      run: |
        apk update
        apk add rsync openssh-client-common

    - name: Restore SSH key
      shell: sh
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "${{ inputs.privkey }}" | base64 -d > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - name: Add server to known_hosts
      shell: sh
      run: |
        ssh-keyscan -4 -p 222 alefbet.net >> ~/.ssh/known_hosts

    - name: Copy files to server
      shell: sh
      run: |
        rsync -avz ${{ inputs.filepath }} github-psec@alefbet.net:/var/www/github/psec