name: Get dependency from the workflow artifacts

inputs:
  name:
    description: The name of the dependency
    required: true

runs:
  using: composite  

  steps:
    - name: Download py3-paho-mqtt2 dependecy
      uses: actions/download-artifact@v4
      with:
        path: downloads
        name: ${{ github.event.inputs.name }}
        run-id: ${{ github.event.workflow_run.id }}

    - name: Uncompress and copy packages 
      shell: sh
      env:
        FILENAME: ${{ inputs.name }}
      run: |
        cd $GITHUB_WORKSPACE/downloads
        if [ -d "$FILENAME" ]; then
          cd "$FILENAME"
        fi
        mkdir -p /home/builder/packages/safecor/x86_64
        cp *.apk /home/builder/packages/safecor/x86_64

    - name: Rebuild and sign the APK index
      shell: sh
      run: |        
        cd /home/builder/packages/safecor/x86_64/
        apk index -d Safecor -o APKINDEX.tar.gz *.apk
        abuild-sign -k /home/builder/.abuild/safecor.rsa -p /etc/apk/keys/safecor.rsa.pub APKINDEX.tar.gz            

    - name: Update repository configuration
      shell: sh
      run: |
        LINE="/home/builder/packages/safecor"
        FILE="/etc/apk/repositories"
        if grep -q "^$LINE\$" "$FILE"; then
          echo "Local repository is already set"
        else
          echo "Adding local repository"
          echo "$LINE" | sudo tee -a $FILE
        fi

        cd /home/builder/packages/safecor
        ln -s x86_64 noarch
        sudo apk update
