name: Get dependency

inputs:
  name:
    description: The name of the dependency
    required: true

runs:
  using: composite  

  steps:
    - name: Download py3-paho-mqtt2 dependecy
      uses: actions/download-artifact@v4
      with:
        name: ${{ github.event.inputs.name }}
        path: $RUNNER_TEMP
        run-id: ${{ github.event.workflow_run.id }}

    - name: Uncompress and copy packages 
      shell: sh
      env:
        FILENAME: ${{ github.events.inputs.name }}
      run: |
        cd $RUNNER_TEMP
        if [ -f "$FILENAME.zip" ]; then
          unzip -o "$FILENAME.zip" -d /home/builder/packages/psec/x86_64
        else 
          cp *.apk /home/builder/packages/psec/x86_64
        fi

    - name: Rebuild and sign the APK index
      shell: sh
      run: |
        apk index -o /home/builder/packages/psec/x86_64/APKINDEX.tar.gz /home/builder/packages/psec/x86_64/*.apk
        abuild-sign /home/builder/packages/psec/x86_64/APKINDEX.tar.gz
