name: Get dependency

inputs:
  name:
    description: The name of the dependency
    required: true

runs:
  using: composite  

  steps:
    - name: Download py3-paho-mqtt2 dependecy
      uses: actions/download-artifact@v4
      with:
        path: downloads
        name: ${{ github.event.inputs.name }}
        run-id: ${{ github.event.workflow_run.id }}

    - name: Uncompress and copy packages 
      shell: sh
      env:
        FILENAME: ${{ inputs.name }}
      run: |
        cd $GITHUB_WORKSPACE/downloads
        if [ -d "$FILENAME" ]; then
          cd "$FILENAME"
        fi        
        mkdir -p /home/builder/packages/psec/x86_64
        cp *.apk /home/builder/packages/psec/x86_64

    - name: Rebuild and sign the APK index
      shell: sh
      run: |        
        cd /home/builder/packages/psec/x86_64/
        apk index -d PSEC -o APKINDEX.tar.gz *.apk
        abuild-sign -k /home/builder/.abuild/psec.rsa -p /etc/apk/keys/psec.rsa.pub APKINDEX.tar.gz            

    - name: Update repository configuration
      shell: sh
      run: |
        LINE="/home/builder/packages/psec"
        FILE="/etc/apk/repositories"
        if grep -q "^$LINE\$" "$FILE"; then
          echo "Local repository is already set"
        else
          echo "Adding local repository"
          echo "$LINE" | sudo tee -a $FILE
        fi

        sudo apk update

        # Vérification
        echo "=== Contenu du dépôt ==="
        ls -la /home/builder/packages/psec/x86_64/
        echo "=== Recherche du paquet ==="
        apk search -e ${{ inputs.name }} || echo "Paquet non trouvé !"

    - name: Debug repository
      shell: sh
      run: |
        echo "=== Structure du dépôt ==="
        find /home/builder/packages/psec -type f
        
        echo "=== Contenu de l'index ==="
        tar -tzf /home/builder/packages/psec/x86_64/APKINDEX.tar.gz
        
        echo "=== Paquets dans l'index ==="
        tar -xzOf /home/builder/packages/psec/x86_64/APKINDEX.tar.gz APKINDEX | grep "^P:" | head -5
        
        echo "=== Repositories configurés ==="
        cat /etc/apk/repositories
        
        echo "=== Cache APK ==="
        sudo apk cache info